[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[cursor.style]
shape = "Beam"

[font]
size = 12

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "JMesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10
